### ISSUE TITLE
Result text option incomplete

### ISSUE THREAD

**Issue by hamzahali** [goldhat/quizmaster#110]
Result text is not having option for graduation or conditional. like it was in quiz pro

This is much needed

It used to come like this
This text will be displayed at the end of the quiz (in results). (this text is optional)
Activate graduation

**Comment by goldhat** [comment]
Thanks for reporting this. You're absolutely right, Graduations has been removed from the Quiz Settings, and the templates for display. This was a difficult choice because yes it's definitely a good feature. We would have liked to actually estimate what percentage of sites use Graduations, and if they liked how it works. Our approach with QuizMaster is to make the core plugin leaner, we've stripped other features like Leaderboard, and reduced the total question types.

What we've added, is a lot more support for extending the plugin. WP Pro Quiz was almost impossible to extend, even to do basic customizations (there was no overridable templates). We've added approx. 30 templates that can be overridden at the theme layer. And there are some new hooks, and classes that developers will be able to use to build addons. 

Graduations is on our list of official addons that we plan to build. By having it as an addon (QuizMaster Graduations) we should be able to improve it. For instance a common request for WP Pro Quiz was support for PDF certificates that could be awarded to students that pass quizzes. These are 2 different features, but we might bundle them together. Because to configure awarding certificates, you have to be able to determine what was the passing grade. 

Another reason we stripped some of the features out of core is because we want to encourage other developers to build QuizMaster addons. There might eventually be 2 or 3 different plugins for Graduations and Certificates. And people can decide which one suits them best, or adapt them. 

I'll leave this issue open and we'll organize it later, thanks again for posting it.

**Comment by hamzahali** [comment]
Thanks for the extensive reply, 

1. Got it, i think conditional text depending on results is very important at the end of quiz. 

2. What is the approximate release date for stable version of quizmaster?

3. Current version asked me paid version of ACF

**Comment by goldhat** [comment]
We're aiming to have the full V1 release completed in June. ACF Pro is required, this requirement is listed in the readme at https://github.com/goldhat/quizmaster/blob/master/readme.txt

**Comment by goldhat** [comment]
The latest v0.8.0 is still pre-production but much more stable than previous versions: https://wordpress.org/plugins/quizmaster/

We've provided FieldMaster plugin as an alternative to ACF Pro on activation. 

QuizMaster Grades enables setup of pass/fail, and specific grades such "over 80% is a B". Grades extension can show a message to students after they take the quiz which is based on what grade they earned, or if they passed/failed. 

Closing ticket for now, feel free to re-open if any further questions.

**Comment by goldhat** [comment]
QuizMaster Grades extension is hosted at https://wordpress.org/plugins/quizmaster-grades/
