### ISSUE TITLE
Question text doesn't actually display

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#45]
The question text isn't actually displayed, the content is missing from the div tag (class="quizMaster_question_text" in the frontend)

**Comment by tdamskov** [comment]
Note that this also occurs when finishing the Quiz and Viewing the questions

**Comment by goldhat** [comment]
This issue is fixed at least in quiz-taking that's the only place I've checked it right now. The problem was the code was using an older method of loading the Questions, by passing an array of the field data. That works mostly, but as the field names are changed (adding common prefixes like "qm_qe") that field loading method won't strip the prefixes. 

Now that the questions are loaded "By ID" and the field names have that prefix stripped, it's possible this will break something else. For future changes, model QuestionMapper->fetchAll() is where the questions are loaded for the quiz take.
