### ISSUE TITLE
Trigger testing

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#49]
Since only one trigger has been added it's not possible to test if various types of triggers can be selected and if they trigger correctly.

Recommendation: Add a new trigger for debugging purposes. An example: "Completed Quiz at 80% score or more"

**Comment by goldhat** [comment]
Second trigger added for 100% score. Added some filters that help to add triggers, did not quite achieve the point where an outside dev could add them because it's one thing to add the trigger, it's another to process it. For now it won't be possible to extend triggers, but we could change that in the future. It's easy enough for us to add new triggers though because we can easily duplicate the processing methods we're using already.
