### ISSUE TITLE
Adding Question to Quiz with dropdown - needs filtering

### ISSUE THREAD

**Issue by tdamskov** [goldhat/QuizMaster#52]
When adding Questions to a particular Quiz, one selects the Question from a dropdown. However, all available questions display inside the dropdown making it at best cumbersome to search in a large pool of questions.

Filters to select both/either tags and categories would be extremely useful when the system has many quizzes and thousands of questions. Performance-wise it will also greatly reduce query time. Saving the filter states for this Quiz would be necessary so when the user returns, one doesn't need to re-select the filters.

**Comment by goldhat** [comment]
That would likely be a lot of work using ACF. We'd have to inject those filters in before the question select. We couldn't or should use ACF fields because it would mean saving those fields associated with every question, which sounds like an awful duplication. Then we have the problem of applying the filtering to the select list, and having it still work with the search inside that select. 

More likely if we wanted to improve this area we'd move away from the ACF questions tab, and build a new metabox under the question options where we'd custom build a question selector. This could be as you describe some filters, and maybe the list would not be in a select but in a kind of text form where the user could click on them to have them drop into the question pool.
